### ISSUE TITLE
Fehler beim Anzeigen des Stundenplans als PDF

### ISSUE THREAD

**Issue by Jintzo** [Jupiterrr/Vorlesungsverzeichnis#37]
Drücke ich auf `/timetable` auf *download (.pdf)*, so erscheint ein Fehler 404 (siehe Screenshot) sowohl bei farbig als auch bei schwarz-weiß.
![screenshot from 2015-08-30 16 58 27](https://cloud.githubusercontent.com/assets/5368029/9567813/9d78751a-4f38-11e5-8046-f5611a2846c6.png)

**Comment by Jupiterrr** [comment]
Fixed. Danke für den Hinweis.
