### ISSUE TITLE
Persona alternative

### ISSUE THREAD

**Issue by jonashaag** [Jupiterrr/Vorlesungsverzeichnis#38]
https://mail.mozilla.org/pipermail/persona-notices/2016/000005.html

> Persona.org and related domains will be taken offline on November 30th,
> 2016.
> If you run a website that relies on Persona, you will need to implement
> an alternative login solution for your users.

**Comment by Jupiterrr** [comment]
Ja, ist ziemlich kacke. Ich werde vielleicht nochmal versuchen Zugang zum KIT Loginsystem zu bekommen, werde vermutlich (wieder) eine Absage oder keine Antwort bekommen und dann wohl auf Email+Passwort-Authentifizierung wechseln.

**Comment by orzechow** [comment]
Was spricht gegen OpenID?

**Comment by Jupiterrr** [comment]
User experience. Man braucht erstmal irgendein Anbieter und dann muss man sich diese Url merken. Ist irgendwie nicht so super. Dann gäbe es natürlich noch die Möglichkeit, die OAuth Loginbuttons anzubieten. Ich werde vermutlich erst nochmal etwas abwarten ob nicht doch noch irgendwer Persona fortführt.

**Comment by pschichtel** [comment]
Ich hab nach einer Neuinstallation meine Session verloren und Persona zeigt mir jetzt nur noch an, das der Service down ist. Ich würde sagen, dieser issue hat jetzt eine etwas höhere Priorität.

**Comment by phil-opp** [comment]
Ein paar Alternativen: [Persona Migration Suggestions and Guidelines](https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers#Migration_Suggestions_and_Guidelines)

**Comment by pschichtel** [comment]
Login per Email klingt nach einer guten passwortlosen Alternative die mir einfach zu implementieren scheint.

**Comment by Jupiterrr** [comment]
Es hat lange gedauert aber ich habe Persona letzte Woche ersetzt und der Login funktioniert jetzt wieder. Ich verwende jetzt Auth0. Passwordless wollte ich nicht aus Usability Gründen.
