### ISSUE TITLE
Reduce the tree height of Vorlesungsverzeichnis

### ISSUE THREAD

**Issue by suluke** [Jupiterrr/Vorlesungsverzeichnis#43]
I was wondering if there might be any plans to address this problem: As a computer science master student, I have 6 columns to click through to finally get to the lectures I want: Computer Science Faculty > Lectures for computer science students > Master > Other deepening events of choice >  Specializations > {Concrete specialization} > {Concrete lecture}.

I guess this is a direct consequence from the data provided by KIT. Still, it might be possible to improve this workflow by attaching some sensible defaults to the user (e.g. Faculty+Course+Degree, whereas HOC/SPZ etc. can be accessed from a different menu) to be able to skip some levels in the tree.

**Comment by Jupiterrr** [comment]
I'm always looking for solution that works for everyone and in this case for every faculty. Sadly there is no common structure in the subtrees, that makes it hard to set some defaults or anything.
The only sensible default I can think of is preselecting the faculty.
